apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-zero-trust
  namespace: default
spec:
  selector:
    matchLabels:
      app: wisecow
  file:
    matchPaths:
      - path: "/usr/local/bin/wisecow.sh"
        action: Block
  process:
    matchPaths:
      - path: "/usr/local/bin/wisecow.sh"
        action: Block
